(source (git https://github.com/tmattio/spin-rescript.git))
(config username "Ryan Cross")
(config project_name "PDG Lookup")
(config ci_cd Github)
(config syntax Reason)
(config project_snake pdg_lookup)
(config css_framework None)
(config project_slug pdg-lookup)
(config project_description "PDG Code Lookup")
