[tool.poetry]
name = "pdg_lookup"
version = "0.1.0"
description = ""
authors = ["CrossR <r.cross@lancaster.ac.uk>"]

[tool.poetry.dependencies]
python = "^3.8"
particle = "^0.13.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
